spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.show_sql=true
#logging.level.org.hibernate.SQL=DEBUG  #dovrebbe mostrare sql nativo
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update  

spring.datasource.url=jdbc:mysql://localhost:3306/UsersManagement?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.generate-ddl=true

#Gestione della pagina di errore
spring.mvc.servlet.path=/
server.error.path=/error



